spring:
  application:
    name: demo-gateway
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      server-addr: nacos.cluster.com:8848
      config:
        namespace: DEMO
