spring:
  application:
    name: erp-gateway
  config:
    import: consul:consul.cluster2.com:80
  cloud:
    consul:
      config:
        acl-token: 7e6ce9c4-99ff-bffd-e05b-bef52c207fd8
        format: YAML
        prefixes:
          - "dev-${spring.application.name}"
  profiles:
    active: local