spring:
  application:
    name: erp-gateway
  config:
    import: consul:consul.cluster2.com:80
  cloud:
    consul:
      config:
        acl-token: 995c639f-ee48-f6e3-c6bc-ae5332e93b7f
        format: YAML
        prefixes:
          - "dev-${spring.application.name}"
  profiles:
    active: local