server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: portal
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/erp-portal/**
          filters:
            - StripPrefix=1