spring:
  application:
    name: erp-gateway
  config:
    import: optional:consul:consul.cluster2.com:80
  cloud:
    consul:
      config:
        acl-token: anonymous
        format: YAML
        prefixes:
          - "dev-${spring.application.name}"
  profiles:
    active: local