server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: demo-portal
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/demo-portal/**
          filters:
            - StripPrefix=1
springdoc:
  swagger-ui:
    urls:
      - name: demo-portal
        url: /v3/api-docs/demo-portal