spring:
  application:
    name: demo-gateway
  config:
    import: nacos:${spring.application.name}.yml
  cloud:
    nacos:
      server-addr: nacos.cluster.com:8848
      config:
        file-extension: yml
        namespace: DEMO