spring:
  application:
    name: erp-gateway
  config:
    import: optional:consul:consul.cluster.com:80
  cloud:
    consul:
      config:
        acl-token: anonymous
        format: YAML
        prefixes:
          - "dev-erp-gateway"
  profiles:
    active: local