spring:
  application:
    name: erp-file-resolve
  config:
    import: optional:consul:consul.cluster.com:80
  cloud:
    consul:
      config:
        acl-token: anonymous
        format: YAML
        prefixes:
          - "dev-erp-common"
          - "dev-erp-file-resolve"
  profiles:
    active: local