spring:
  application:
    name: demo-file-resolve
  config:
    import: optional:consul:consul.cluster.com:80
  cloud:
    consul:
      config:
        acl-token: anonymous
        format: YAML
        prefixes:
          - "dev-demo-common"
          - "dev-demo-file-resolve"