spring:
    datasource:
      url: jdbc:mysql://localhost:3306/czy_oa?&useSSL=false
      username: root
      password: sasa
      driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.czy.entity.po
  global-config:
    #刷新mapper 调试神器
        db-config:
          #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
          id-type: auto
          column-underline: false
          table-prefix: oa_



