spring:
  cloud:
    consul:
      config:
        enabled: false
    stream:
      rabbit:
        bindings:
          input-in-0:
            consumer:
              enable-batching: true
              batch-size: 5
              receive-timeout: 200
      bindings:
        input-in-0:
          group: someGroup
          consumer:
            batch-mode: true
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: admin:***REMOVED***@192.168.2.21:5672
