stream-group-1: "stream"
server:
  port: 8080
spring:
  application:
    name: demo-stream
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:demo-common.yml
  cloud:
    nacos:
      server-addr: nacos.cluster.com:8848
      config:
        namespace: DEMO
    stream:
      bindings:
        rabbitInput11-in-0:
          destination: input1Topic
          group: ${stream-group-1}
          binder: rabbit
        rabbitInput12-in-0:
          destination: input2Topic
          group: ${stream-group-1}
          consumer:
            batch-mode: true
          binder: rabbit
        kafkaInput21-in-0:
          destination: input3Topic
          group: ${stream-group-1}
          binder: kafka
        kafkaInput22-in-0:
          destination: input4Topic
          group: ${stream-group-1}
          binder: kafka
          consumer:
            batch-mode: true
        kafkaInput23-in-0:
          destination: input5Topic
          binder: kafka
      rabbit:
        bindings:
          rabbitInput11-in-0:
            consumer:
              acknowledge-mode: manual
          rabbitInput12-in-0:
            consumer:
              enable-batching: true
              batch-size: 100
              receive-timeout: 200
      kafka:
        bindings:
          kafkaInput21-in-0:
            consumer:
              auto-rebalance-enabled: true
          kafkaInput22-in-0:
            consumer:
              auto-rebalance-enabled: true
    function:
      definition: rabbitInput11;rabbitInput12;kafkaInput21;kafkaInput22;
#      binders:
#        rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                addresses: ${spring.rabbitmq.addresses}
#        kafka:
#          type: kafka
#          environment:
#            spring:
#              kafka:
#                bootstrap-servers: ${spring.kafka.bootstrap-servers}