server:
  port: 8082
spring:
  rabbitmq:
    addresses: admin:***REMOVED***@192.168.2.21:5672
  cloud:
    consul:
      enabled: false
    stream:
      rabbit:
        bindings:
          input1-in-0:
            consumer:
              enable-batching: true
              batch-size: 1000
              receive-timeout: 200
      bindings:
        input1-in-0:
          group: someGroup
          consumer:
            batch-mode: true
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: admin:***REMOVED***@192.168.2.21:5672
