stream-group-1: "stream"
spring:
  profiles:
    include: local
  application:
    name: demo-stream
  config:
    import: optional:consul:consul.cluster.com:80
  cloud:
    consul:
      config:
        format: YAML
        prefixes:
          - "demo-common"
    stream:
      bindings:
        rabbitInput11-in-0:
          destination: input1Topic
          group: ${stream-group-1}
          binder: rabbit
        rabbitInput12-in-0:
          destination: input2Topic
          group: ${stream-group-1}
          consumer:
            batch-mode: true
          binder: rabbit
        kafkaInput21-in-0:
          destination: input3Topic
          group: ${stream-group-1}
          binder: kafka
        kafkaInput22-in-0:
          destination: input4Topic
          group: ${stream-group-1}
          binder: kafka
          consumer:
            batch-mode: true
      rabbit:
        bindings:
          rabbitInput11-in-0:
            consumer:
              acknowledge-mode: manual
          rabbitInput12-in-0:
            consumer:
              enable-batching: true
              batch-size: 100
              receive-timeout: 200
      kafka:
        bindings:
          kafkaInput21-in-0:
            consumer:
              auto-rebalance-enabled: true
          kafkaInput22-in-0:
            consumer:
              auto-rebalance-enabled: true
      function:
        definition: rabbitInput11;rabbitInput12;kafkaInput21;kafkaInput22;
#      binders:
#        rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                addresses: ${spring.rabbitmq.addresses}
#        kafka:
#          type: kafka
#          environment:
#            spring:
#              kafka:
#                bootstrap-servers: ${spring.kafka.bootstrap-servers}