management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8082
stream-group-1: "stream"
kafka-address: 192.168.2.18:9092,192.168.2.18:9093
rabbit-address: admin:***REMOVED***@192.168.2.21:5672
spring:
  rabbitmq:
    addresses: ${rabbit-address}
  kafka:
    bootstrap-servers: ${kafka-address}
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    consul:
      enabled: false
    stream:
      bindings:
        rabbitInput11-in-0:
          destination: input1Topic
          group: ${stream-group-1}
          binder: rabbit
        rabbitInput12-in-0:
          destination: input2Topic
          group: ${stream-group-1}
          consumer:
            batch-mode: true
          binder: rabbit
        kafkaInput21-in-0:
          destination: input3Topic
          group: ${stream-group-1}
          binder: kafka
      rabbit:
        bindings:
          rabbitInput11-in-0:
            consumer:
              acknowledge-mode: manual
          rabbitInput12-in-0:
            consumer:
              enable-batching: true
              batch-size: 100
              receive-timeout: 200
      kafka:
        bindings:
          kafkaInput21-in-0:
            consumer:
              auto-rebalance-enabled: true
      function:
        definition: rabbitInput11;rabbitInput12;kafkaInput21
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: ${rabbit-address}
        kafka:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: ${kafka-address}