server:
  port: 8082
spring:
  rabbitmq:
    addresses: admin:***REMOVED***@192.168.2.21:5672
  cloud:
    consul:
      enabled: false
    stream:
      rabbit:
        bindings:
          input1-in-0:
            consumer:
              enable-batching: true
              batch-size: 100
              receive-timeout: 200
          input2-in-0:
            consumer:
              acknowledge-mode: manual
      bindings:
        input1-in-0:
          destination: input1Topic
          group: "stream"
          consumer:
            batch-mode: true
        input2-in-0:
          destination: input2Topic
          group: "stream"
      function:
        definition: input1;input2
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: admin:***REMOVED***@192.168.2.21:5672