spring:
  application:
    name: erp-portal
  config:
    import: consul:consul.cluster2.com:80
  cloud:
    consul:
      config:
        format: YAML
        prefixes:
          - "dev-erp-common"
          - "dev-erp-portal"
        acl-token: 7e6ce9c4-99ff-bffd-e05b-bef52c207fd8
  profiles:
    active: local