spring:
  datasource:
    url: jdbc:mysql://localhost:5306/erp_java?&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
    username: root
    password: ***REMOVED***
  data:
    mongodb:
      uri: mongodb://127.0.0.1:5017
      database: erp_java
      username: admin
      authentication-database: admin
      password: ***REMOVED***