spring:
  application:
    name: erp-portal
  config:
    import: consul:consul.cluster2.com:80
  cloud:
    consul:
      config:
        format: YAML
        prefixes:
          - "${ENV_NAME}-${spring.application.name}"
  profiles:
    active: local