spring:
  application:
    name: demo-portal
  config:
    import: optional:consul:consul.cluster.com:80
  cloud:
    consul:
      config:
        format: YAML
        prefixes:
          - "demo-common"
          - "demo-portal"
      discovery:
        instance-id: ${POD_NAME:}