server:
  port: 8080
spring:
  application:
    name: demo-portal
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:demo-common.yml
  cloud:
    nacos:
      server-addr: nacos.czy21.com:8848
      config:
        namespace: DEMO