server:
  port: 8080
spring:
  application:
    name: erp-portal
  config:
    import: consul:consul.cluster2.com:80
  cloud:
    consul:
      config:
        format: YAML
        prefixes:
          - "dev-erp-common"
          - "dev-${spring.application.name}"