spring:
  application:
    name: erp-portal
  config:
    import: optional:consul:consul.cluster.com:80
  cloud:
    consul:
      config:
        format: YAML
        prefixes:
          - "dev-erp-common"
          - "dev-erp-portal"
  profiles:
    active: local