
spring:
  datasource:
    url: jdbc:mysql://std003-internal.softium.cn:3306/erp_java_local?user=root&password=123456@TM&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
  data:
    mongodb:
      uri: mongodb://admin:***REMOVED***@127.0.0.1:22717/erp_java_local?authSource=admin
    neo4j:
      username: neo4j
      password: ***REMOVED***
  rabbitmq:
    host: 192.168.110.140
    username: root
    password: root
    port: 5672
  kafka:
    bootstrap-servers: 192.168.168.140:9092,192.168.168.140:9093
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: consumers
    streams:
      bootstrap-servers: 192.168.168.140:9092,192.168.168.140:9093
server:
  port: 8075