server:
  port: 8080
spring:
  application:
    name: portal
#  config:
#    import: consul:consul.internal-home.com:80
  cloud:
    consul:
      host: consul.internal-home.com
      port: 80
      config:
        format: yaml
        prefixes: dev
        default-context: ${spring.application.name}
        enabled: false
  profiles:
    active: local
