spring:
  application:
    name: erp-portal
  config:
    import: optional:consul:consul.cluster2.com:80
  cloud:
    consul:
      config:
        acl-token: anonymous
        format: YAML
        prefixes:
          - "dev-erp-common"
          - "dev-erp-portal"
  profiles:
    active: local