server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: 192.168.2.25:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: consumers