server:
  port: 8080
spring:
  profiles:
    active: override
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://192.168.2.4:3306/erp_java_local?user=admin&password=***REMOVED***&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
  data:
    mongodb:
      uri: mongodb://192.168.2.4:27017/erp_java_local
  redis:
    host: 192.168.2.4
    port: 6379
    timeout: 3600
  kafka:
    bootstrap-servers: 192.168.247.140:9092,192.168.247.140:9093
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: consumers
    streams:
      bootstrap-servers: 192.168.247.140:9092,192.168.247.140:9093
      application-id: kafka-streams-demo
      properties:
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#            deserializer: org.apache.kafka.common.serialization.LongDeserializer
        spring:
          json:
            trusted:
              packages: com.team.portal.kafka

mybatis-plus:
  mapper-locations: classpath*:mapper/**/**.xml
  type-aliases-package: com.team.domain.entity
  type-aliases-super-type: com.team.infrastructure.base.BaseEntity
  global-config:
    db-config:
      id-type: uuid
    banner: false

logging:
  level:
    com.team.domain.mapper: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    org.springframework.jdbc.core: debug

ali:
  access-key:
    id: 2222
    secret: 12345679
  pay:
    public-key-file: ./alipay/ali-public
    app-private-key-file: ./alipay/app-private
    server-url: https://openapi.alipaydev.com/gateway.do
    app:
      sample1:
        app-id: 2016102900777119
        scene: bar_code
  oss:
    example1:
      end-point: www.baidu.com
  sms:
    example1:
      sign-name: 测试名称
      template-code: SMS_12345678