server:
  port: 8075
spring:
  profiles:
    active: override
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/erp_java?user=admin&password=***REMOVED***&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/erp_java
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3600
  jpa:
    show-sql: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.team.domain.entity
  type-aliases-super-type: com.team.infrastructure.base.BaseEntity
  global-config:
    db-config:
      id-type: uuid
    banner: false

pagehelper:
  auto-dialect: mysql # 指定数据库，不指定的话会默认自动检测数据库类型
  reasonable: true    # 如果pageIndex<0是,查询第一页,如果pageIndex>pageSizes查询最后一页
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true  #pageSize为0时,不执行分页,返回全部结果

logging:
  level:
    com.team.domain.mapper: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

ali:
  access-key:
    id: 2222
    secret: 12345679
  pay:
    public-key-file: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn7MbnuJcPuYIVSxZMiqxJc+4tyKdh4rGNe73gKEpoZpxq/xQFzmmvysANZcPcda/c0zkO9No8A3rzX4BU+15pr1Ee7ceXCz2u/PJq9uimZ2AVy5VjzUAC2u4oZP09PRJetK/ztwn+mXmSKfE8eo3ZrqRKbpEacio6SQhcmjZbh9ENmWcA8m92KnZEDFwKkV/WInqXw4yQ949BpmNPavyg4nf+8bTWo0PjTqzYMSH6zMWOQJHJBYpwIZXXJjHC8trRKebBSJ24AdwWszPpZrNSOF5BkQwjuAAos8kmxK3y3tS/NtAyDp0k+GPqQLOfWNg6tf6mmnxfIMIrbSwdDuhWwIDAQAB
    app-private-key-file: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDFpZEHFXKO3OH382pHR/KbVicFAaDRmrXaYGbOpWys12EKoUyt2Cnb8EyJtKfoLvuaqaqbmWgEsSe0VYGKgNtwubyy0ZsBjdMOFXBQuVlkZCq3in0kLtc0GsWL9WnNPFRCaOZSvXY0rPssY295bpRxvqS5Tk3MOH7meJ9xC/ob/4cD42M8qi+3cvPNGfcoY5RXVKTXoK2sV2bedOmK8fRHsY9Z7v11m6kW9BN8yHQ9K1SKTstrSJV3HGk3HkLTVrCK+aJQHCJ10bVfVphq8+RzPIr/a47M//w8CaNxMQQ8opYWGLr6eGDm1+n+7Pzm44/Gzd+VIXYgFbDyMQSs1yQBAgMBAAECggEAX+cOkBlgFOIo419BWoUWuzj6hftcRViElQnh2LN8IAICHF5YDqKs7QOUn90A/DCP9WQOXKH7TwuG8IHs8X/E+tWlMj9yrzZaCqNsdD77mTLhZ13TixMPaUD0Sg0y4Vs8p1yvJca47KZi2g8FsC5v6SFQXHoaVdWz/bDZ7Mia+6oO08ZLZWxfikhr9fHVrAszA6QwFweZUsXIu8Z+GcIs4J5FDPG1E7eiAOKZA9OwUpE2hBYRz6WF/nvjW5EMqJxITjKk/IjVvmJy/eNKoADv7zSHJP5t208IH0U/+a7evnIAH7d8XWazMzh+fQRLDYQ+lsngQ5OX91D2zQb8tOnigQKBgQDw1TeB1cdtgjNQGlaLF8tlnxlZeV5i1/Csaa0Pfs2Fw2Ukq8KFQRBhO++Jl/fBRmu+27o04C3ZlKJK9OcZGlJ9kt9TymC39VkAIbbrNZ/TSuvY83NIOLLFiCttBQiCovm5eZglbtXnG63oVpWGHgazeP1BRO2TuHs3MwZV9FWzRQKBgQDSGBbcF0k/WlhBXmnwG2g10DIehKU2M6jn6Wt7wpeopleTvkjKVtUrMTc1SBYG9XKt60ZrmvPrDzi8HRWLBYTeMgqRHwcSFV5bNAqlIagtXVjS0L0yFdcSZKyQdz6oQ2ss+MtSl4ZDOq30FrSGa3wYTX05izqNwaFyOlJ4I/C7jQKBgDlgsy7NvgvLH2qQO9o7uwvlEecNUX1/MSoCq2arsU+TM/++pEOXMs3Xt8QyXqa/nmAEfaKnXoUeMmRlYMHMUab1XRvbdZueaqvrXGdBiWiPyw0PQ4ILcBw7ywzYTCTDq3eTDrqsY24CXDakmk8vzCzqQHxSbb/qDgEiuPm1ks15AoGAeXFZTXHcclWL7IVh4VxGWcz2G7P7OCCWgy/nZIuwVNmKiCmXM/cLk8MIMbFwoichWi1E8JCKbJbI6dw6Brly+2mbuBViZe6aM0ga2ydgapCp9nqY0qnTP5uYMI3tVyBZhI5wIVbbUmNKCG1TftwEyJuKRkgX2bdS1o+l+jJ0RkUCgYByjstxwxdAXYj1R2b+D9l7/V67NsRRnD6ACKJcv8Rpy2l8F9EOXcQUT3rRKeUS/SrMYy0t28cM36C5M5FJFrhG/+78y8/Pny3WuU+raNVpVPqDrjKdGWuiJtU4iyVKd45dnKEtUrxqNdp6J8bWn6WGKRN/FmPJiZwbsCWa12s/Vw==
    app:
      sample1:
        app-id: 2016102900777119
        scene: bar_code
  oss:
    example1:
      end-point: www.baidu.com
  sms:
    example1:
      sign-name: 测试名称
      template-code: SMS_12345678