server:
  port: 8080
spring:
  application:
    name: erp
  profiles:
    active: override
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://192.168.2.3:3306/erp_local?user=admin&password=***REMOVED***&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
  data:
    mongodb:
      uri: mongodb://admin:***REMOVED***@192.168.2.3:27017/erp_local?authSource=admin
  redis:
    host: 192.168.2.3
    port: 6379
    timeout: 3600
    password: ***REMOVED***
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:mapper/**/**.xml
  type-aliases-package: com.team.domain.entity
  type-aliases-super-type: com.team.infrastructure.base.BaseEntity
  global-config:
    db-config:
      id-type: uuid
    banner: false

logging:
  level:
    com.team.domain.mapper: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    org.springframework.jdbc.core: debug
    org.springframework.data.mongodb.core: debug

ali:
  access-key:
    id: 2222
    secret: 12345679
  pay:
    public-key-file: ./alipay/ali-public
    app-private-key-file: ./alipay/app-private
    server-url: https://openapi.alipaydev.com/gateway.do
    app:
      sample1:
        app-id: 2016102900777119
        scene: bar_code
  oss:
    example1:
      end-point: www.baidu.com
  sms:
    example1:
      sign-name: 测试名称
      template-code: SMS_12345678
