spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp_java?&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
    username: root
    password: sasa
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: erp_java