server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${db-host}:9092,${db-host}:9093,${db-host}:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#pulsar:
#  service-url: pulsar://localhost:6650
