spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3372/erp?&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
      username: root
      password: Czy.101048
  data:
    mongodb:
      uri: mongodb://localhost:3270
      database: erp
  redis:
    password: team3059
allowed-origin:
  url: http://47.106.191.56:8090
authentication:
  token-expire-time: 30
