server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: 192.168.2.25:9092,192.168.2.25:9093,192.168.2.25:9094
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: consumers