server:
  port: 8080
  servlet:
    context-path: /portal
spring:
  application:
    name: portal
  config:
    import: consul:consul.internal-home.com:80
  cloud:
    consul:
      config:
        format: yaml
        prefixes: ${ENV_NAME}
        default-context: ${spring.application.name}
        enabled: true
      enabled: true
  profiles:
    active: local
