spring:
  datasource:
    url: jdbc:mysql://localhost:5306/erp_java?user=admin&password=***REMOVED***&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
  data:
    mongodb:
      uri: mongodb://admin:***REMOVED***@127.0.0.1:5017/erp_java?authSource=admin