spring:
  datasource:
    url: jdbc:mysql://localhost:3306/erp_java?user=root&password=sasa&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/erp_java