server:
  port: ${{{param_injected['param_api_host_port']}}}
spring:
  datasource:
    url: jdbc:mysql://${{{param_main_db_mysql_host}}}:${{{param_main_db_mysql_port}}}/${{{param_main_db_name}}}?user=${{{param_main_db_mysql_user}}}&password=${{{param_main_db_mysql_pass}}}&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
  data:
    mongodb:
      uri: mongodb://${{{param_main_db_mongo_host}}}:${{{param_main_db_mongo_port}}}/${{{param_main_db_name}}}
    neo4j:
      username: neo4j
      password: ***REMOVED***
  redis:
    host: ${{{param_injected['param_main_redis_host']}}}
    port: 6379
    timeout: 3600
  rabbitmq:
    host: ${{{param_injected['param_main_rabbit_host']}}}
    port: 5672
    username: root
    password: root