server:
  port: ${{{param_injected.param_api_host_port}}}
spring:
  datasource:
    url: jdbc:mysql://${{{param_main_db_host}}}:${{{param_main_db_mysql_port}}}/${{{param_main_db_name}}}?user=${{{param_main_db_mysql_user}}}&password=${{{param_main_db_mysql_pass}}}&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
  data:
    mongodb:
      uri: mongodb://${{{param_main_db_host}}}:${{{param_main_db_mongo_port}}}/${{{param_main_db_name}}}
