pipeline {
    agent any
    stages {
        environment {
            HOME = "${env.WORKSPACE}"
            image_tag="play"
        }
        stage('init') {
            steps {
                sh 'pip3 install -r script/requirements.txt && rm -rf ___output/'
            }
        }
        stage('build') {
            failFast true
            parallel {
                stage('db') {
                    steps {
                        sh 'sh shell/play/rebuild_rdb.sh --skip-rm-output'
                    }
                }
                stage('api') {
                    steps {
                        sh 'sh shell/play/build_api_image.sh --param param_api_image_tag="${image_tag}" --skip-rm-output'
                    }
                }
                stage('web') {
                    steps {
                        sh 'echo "build_web"'
                    }
                }
            }
        }
        stage('deploy'){
            steps{
                sh 'sh shell/play/start_api.sh --param param_api_image_tag="${image_tag}"--skip-rm-output'
            }
        }
    }
}
