spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:5306/erp_java?&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
      username: root
      password: ***REMOVED***
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: erp
allowed-origin:
  url: http://localhost:8080
authentication:
  token-expire-time: 0