spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3372/erp?&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
      username: root
      password: czy101048
  redis:
    password: team3059
