spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/erp?&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&useUnicode=true
      username: root
      password: sasa