management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8083
spring:
  kafka:
    bootstrap-servers: 192.168.2.18:9092,192.168.2.18:9093
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    consul:
      enabled: false
