server:
  port: 8075
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/czy_oa?&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.czy.entity.po
  type-aliases-super-type: com.czy.core.universal.BaseEntity
  global-config:
    refresh: true
    db-config:
      id-type: uuid
      table-prefix: oa_
      db-type: mysql
