version: '3.7'

services:

  mongo:
    image: mongo:4.0
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - /data/volumes/mongo/:/data/db/
      - /data/config/mongo/:/data/configdb/
    command: --config /data/configdb/mongod.conf
    restart: always